<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="factory" nsURI="http://www.example.org/factory" nsPrefix="factory">
  <eClassifiers xsi:type="ecore:EClass" name="FactorySpecification" eSuperTypes="#//IdentifiableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedFactories" upperBound="-1"
        eType="#//Factory"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedEmployees" upperBound="-1"
        eType="#//Employee"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedMachines" upperBound="-1"
        eType="#//Machine"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedProducts" upperBound="-1"
        eType="#//Product"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Factory" eSuperTypes="#//IdentifiableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="employees" upperBound="-1"
        eType="#//Employee"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="machines" upperBound="-1"
        eType="#//Machine"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="createdProducts" upperBound="-1"
        eType="#//Product"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Machine" eSuperTypes="#//IdentifiableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Employee" eSuperTypes="#//IdentifiableElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Product" eSuperTypes="#//IdentifiableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constructionProcess" eType="ecore:EClass ../../de.mdelab.languages.productionschema/model/productionschema.ecore#//ProductionSchema"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IdentifiableElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
  </eClassifiers>
</ecore:EPackage>
